FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY api ./api
COPY pipeline ./pipeline

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
